app = "langgraph-gradio-starter"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_URL = "https://langgraph-gradio-starter.fly.dev"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

  [services.http_checks]
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/live"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443