openapi: 3.0.0
info:
  title: LangGraph Gradio Starter API
  version: 1.0.0
  description: FastAPI + Gradio application with LangGraph and OpenRouter integration
servers:
  - url: http://localhost:7860
    description: Local development server
  - url: https://langgraph-gradio-starter.fly.dev
    description: Production server
paths:
  /:
    get:
      summary: Gradio Interface
      description: Main Gradio chat interface
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
  /docs:
    get:
      summary: API Documentation
      description: OpenAPI documentation
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
  /health:
    get:
      summary: Health Check
      description: API health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"